// Code generated by protoc-gen-go. DO NOT EDIT.
// source: byteintellect_protos/pkg/catalog_v1/catalog.proto

package catalog_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/kutty-kumar/byteintellect_protos/pkg/core_v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CategoryDto struct {
	Description          string   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl             string   `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryDto) Reset()         { *m = CategoryDto{} }
func (m *CategoryDto) String() string { return proto.CompactTextString(m) }
func (*CategoryDto) ProtoMessage()    {}
func (*CategoryDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8238c2673550e54a, []int{0}
}

func (m *CategoryDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryDto.Unmarshal(m, b)
}
func (m *CategoryDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryDto.Marshal(b, m, deterministic)
}
func (m *CategoryDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryDto.Merge(m, src)
}
func (m *CategoryDto) XXX_Size() int {
	return xxx_messageInfo_CategoryDto.Size(m)
}
func (m *CategoryDto) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryDto.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryDto proto.InternalMessageInfo

func (m *CategoryDto) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CategoryDto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CategoryDto) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type ProductDto struct {
	CategoryId           string   `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	ManHours             int64    `protobuf:"varint,3,opt,name=man_hours,json=manHours,proto3" json:"man_hours,omitempty"`
	ImageUrl             string   `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductDto) Reset()         { *m = ProductDto{} }
func (m *ProductDto) String() string { return proto.CompactTextString(m) }
func (*ProductDto) ProtoMessage()    {}
func (*ProductDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8238c2673550e54a, []int{1}
}

func (m *ProductDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductDto.Unmarshal(m, b)
}
func (m *ProductDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductDto.Marshal(b, m, deterministic)
}
func (m *ProductDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductDto.Merge(m, src)
}
func (m *ProductDto) XXX_Size() int {
	return xxx_messageInfo_ProductDto.Size(m)
}
func (m *ProductDto) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductDto.DiscardUnknown(m)
}

var xxx_messageInfo_ProductDto proto.InternalMessageInfo

func (m *ProductDto) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

func (m *ProductDto) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ProductDto) GetManHours() int64 {
	if m != nil {
		return m.ManHours
	}
	return 0
}

func (m *ProductDto) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *ProductDto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateCategoryRequest struct {
	Payload              *CategoryDto `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateCategoryRequest) Reset()         { *m = CreateCategoryRequest{} }
func (m *CreateCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCategoryRequest) ProtoMessage()    {}
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8238c2673550e54a, []int{2}
}

func (m *CreateCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCategoryRequest.Unmarshal(m, b)
}
func (m *CreateCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCategoryRequest.Marshal(b, m, deterministic)
}
func (m *CreateCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCategoryRequest.Merge(m, src)
}
func (m *CreateCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCategoryRequest.Size(m)
}
func (m *CreateCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCategoryRequest proto.InternalMessageInfo

func (m *CreateCategoryRequest) GetPayload() *CategoryDto {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateCategoryResponse struct {
	Response             *CategoryDto `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateCategoryResponse) Reset()         { *m = CreateCategoryResponse{} }
func (m *CreateCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCategoryResponse) ProtoMessage()    {}
func (*CreateCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8238c2673550e54a, []int{3}
}

func (m *CreateCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCategoryResponse.Unmarshal(m, b)
}
func (m *CreateCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCategoryResponse.Marshal(b, m, deterministic)
}
func (m *CreateCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCategoryResponse.Merge(m, src)
}
func (m *CreateCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCategoryResponse.Size(m)
}
func (m *CreateCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCategoryResponse proto.InternalMessageInfo

func (m *CreateCategoryResponse) GetResponse() *CategoryDto {
	if m != nil {
		return m.Response
	}
	return nil
}

type UpdateCategoryRequest struct {
	Payload              *CategoryDto `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	CategoryId           string       `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateCategoryRequest) Reset()         { *m = UpdateCategoryRequest{} }
func (m *UpdateCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCategoryRequest) ProtoMessage()    {}
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8238c2673550e54a, []int{4}
}

func (m *UpdateCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCategoryRequest.Unmarshal(m, b)
}
func (m *UpdateCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCategoryRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCategoryRequest.Merge(m, src)
}
func (m *UpdateCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCategoryRequest.Size(m)
}
func (m *UpdateCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCategoryRequest proto.InternalMessageInfo

func (m *UpdateCategoryRequest) GetPayload() *CategoryDto {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UpdateCategoryRequest) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

type UpdateCategoryResponse struct {
	Response             *CategoryDto `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateCategoryResponse) Reset()         { *m = UpdateCategoryResponse{} }
func (m *UpdateCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCategoryResponse) ProtoMessage()    {}
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8238c2673550e54a, []int{5}
}

func (m *UpdateCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCategoryResponse.Unmarshal(m, b)
}
func (m *UpdateCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCategoryResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCategoryResponse.Merge(m, src)
}
func (m *UpdateCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCategoryResponse.Size(m)
}
func (m *UpdateCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCategoryResponse proto.InternalMessageInfo

func (m *UpdateCategoryResponse) GetResponse() *CategoryDto {
	if m != nil {
		return m.Response
	}
	return nil
}

type GetCategoriesRequest struct {
	SearchText           string   `protobuf:"bytes,1,opt,name=search_text,json=searchText,proto3" json:"search_text,omitempty"`
	PerPage              int64    `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	PageNo               int64    `protobuf:"varint,3,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCategoriesRequest) Reset()         { *m = GetCategoriesRequest{} }
func (m *GetCategoriesRequest) String() string { return proto.CompactTextString(m) }
func (*GetCategoriesRequest) ProtoMessage()    {}
func (*GetCategoriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8238c2673550e54a, []int{6}
}

func (m *GetCategoriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCategoriesRequest.Unmarshal(m, b)
}
func (m *GetCategoriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCategoriesRequest.Marshal(b, m, deterministic)
}
func (m *GetCategoriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCategoriesRequest.Merge(m, src)
}
func (m *GetCategoriesRequest) XXX_Size() int {
	return xxx_messageInfo_GetCategoriesRequest.Size(m)
}
func (m *GetCategoriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCategoriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCategoriesRequest proto.InternalMessageInfo

func (m *GetCategoriesRequest) GetSearchText() string {
	if m != nil {
		return m.SearchText
	}
	return ""
}

func (m *GetCategoriesRequest) GetPerPage() int64 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *GetCategoriesRequest) GetPageNo() int64 {
	if m != nil {
		return m.PageNo
	}
	return 0
}

type GetCategoriesResponse struct {
	Result               []*CategoryDto `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Total                int64          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	NextPage             bool           `protobuf:"varint,3,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetCategoriesResponse) Reset()         { *m = GetCategoriesResponse{} }
func (m *GetCategoriesResponse) String() string { return proto.CompactTextString(m) }
func (*GetCategoriesResponse) ProtoMessage()    {}
func (*GetCategoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8238c2673550e54a, []int{7}
}

func (m *GetCategoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCategoriesResponse.Unmarshal(m, b)
}
func (m *GetCategoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCategoriesResponse.Marshal(b, m, deterministic)
}
func (m *GetCategoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCategoriesResponse.Merge(m, src)
}
func (m *GetCategoriesResponse) XXX_Size() int {
	return xxx_messageInfo_GetCategoriesResponse.Size(m)
}
func (m *GetCategoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCategoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCategoriesResponse proto.InternalMessageInfo

func (m *GetCategoriesResponse) GetResult() []*CategoryDto {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetCategoriesResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetCategoriesResponse) GetNextPage() bool {
	if m != nil {
		return m.NextPage
	}
	return false
}

type CreateProductRequest struct {
	Payload              *ProductDto `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateProductRequest) Reset()         { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()    {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8238c2673550e54a, []int{8}
}

func (m *CreateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductRequest.Unmarshal(m, b)
}
func (m *CreateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductRequest.Marshal(b, m, deterministic)
}
func (m *CreateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductRequest.Merge(m, src)
}
func (m *CreateProductRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductRequest.Size(m)
}
func (m *CreateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductRequest proto.InternalMessageInfo

func (m *CreateProductRequest) GetPayload() *ProductDto {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateProductResponse struct {
	Response             *ProductDto `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateProductResponse) Reset()         { *m = CreateProductResponse{} }
func (m *CreateProductResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProductResponse) ProtoMessage()    {}
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8238c2673550e54a, []int{9}
}

func (m *CreateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductResponse.Unmarshal(m, b)
}
func (m *CreateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductResponse.Marshal(b, m, deterministic)
}
func (m *CreateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductResponse.Merge(m, src)
}
func (m *CreateProductResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProductResponse.Size(m)
}
func (m *CreateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductResponse proto.InternalMessageInfo

func (m *CreateProductResponse) GetResponse() *ProductDto {
	if m != nil {
		return m.Response
	}
	return nil
}

type UpdateProductRequest struct {
	Payload              *ProductDto `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ProductId            string      `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateProductRequest) Reset()         { *m = UpdateProductRequest{} }
func (m *UpdateProductRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductRequest) ProtoMessage()    {}
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8238c2673550e54a, []int{10}
}

func (m *UpdateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductRequest.Unmarshal(m, b)
}
func (m *UpdateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductRequest.Merge(m, src)
}
func (m *UpdateProductRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductRequest.Size(m)
}
func (m *UpdateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductRequest proto.InternalMessageInfo

func (m *UpdateProductRequest) GetPayload() *ProductDto {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UpdateProductRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type UpdateProductResponse struct {
	Response             *ProductDto `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateProductResponse) Reset()         { *m = UpdateProductResponse{} }
func (m *UpdateProductResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProductResponse) ProtoMessage()    {}
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8238c2673550e54a, []int{11}
}

func (m *UpdateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductResponse.Unmarshal(m, b)
}
func (m *UpdateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductResponse.Merge(m, src)
}
func (m *UpdateProductResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProductResponse.Size(m)
}
func (m *UpdateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductResponse proto.InternalMessageInfo

func (m *UpdateProductResponse) GetResponse() *ProductDto {
	if m != nil {
		return m.Response
	}
	return nil
}

type GetProductsRequest struct {
	SearchText           string   `protobuf:"bytes,1,opt,name=search_text,json=searchText,proto3" json:"search_text,omitempty"`
	PerPage              int64    `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	PageNo               int64    `protobuf:"varint,3,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductsRequest) Reset()         { *m = GetProductsRequest{} }
func (m *GetProductsRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductsRequest) ProtoMessage()    {}
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8238c2673550e54a, []int{12}
}

func (m *GetProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsRequest.Unmarshal(m, b)
}
func (m *GetProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsRequest.Marshal(b, m, deterministic)
}
func (m *GetProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsRequest.Merge(m, src)
}
func (m *GetProductsRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductsRequest.Size(m)
}
func (m *GetProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsRequest proto.InternalMessageInfo

func (m *GetProductsRequest) GetSearchText() string {
	if m != nil {
		return m.SearchText
	}
	return ""
}

func (m *GetProductsRequest) GetPerPage() int64 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *GetProductsRequest) GetPageNo() int64 {
	if m != nil {
		return m.PageNo
	}
	return 0
}

type GetProductsResponse struct {
	Result               []*ProductDto `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Total                int64         `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	NextPage             bool          `protobuf:"varint,3,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetProductsResponse) Reset()         { *m = GetProductsResponse{} }
func (m *GetProductsResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductsResponse) ProtoMessage()    {}
func (*GetProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8238c2673550e54a, []int{13}
}

func (m *GetProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsResponse.Unmarshal(m, b)
}
func (m *GetProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsResponse.Marshal(b, m, deterministic)
}
func (m *GetProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsResponse.Merge(m, src)
}
func (m *GetProductsResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductsResponse.Size(m)
}
func (m *GetProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsResponse proto.InternalMessageInfo

func (m *GetProductsResponse) GetResult() []*ProductDto {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetProductsResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetProductsResponse) GetNextPage() bool {
	if m != nil {
		return m.NextPage
	}
	return false
}

func init() {
	proto.RegisterType((*CategoryDto)(nil), "catalog.CategoryDto")
	proto.RegisterType((*ProductDto)(nil), "catalog.ProductDto")
	proto.RegisterType((*CreateCategoryRequest)(nil), "catalog.CreateCategoryRequest")
	proto.RegisterType((*CreateCategoryResponse)(nil), "catalog.CreateCategoryResponse")
	proto.RegisterType((*UpdateCategoryRequest)(nil), "catalog.UpdateCategoryRequest")
	proto.RegisterType((*UpdateCategoryResponse)(nil), "catalog.UpdateCategoryResponse")
	proto.RegisterType((*GetCategoriesRequest)(nil), "catalog.GetCategoriesRequest")
	proto.RegisterType((*GetCategoriesResponse)(nil), "catalog.GetCategoriesResponse")
	proto.RegisterType((*CreateProductRequest)(nil), "catalog.CreateProductRequest")
	proto.RegisterType((*CreateProductResponse)(nil), "catalog.CreateProductResponse")
	proto.RegisterType((*UpdateProductRequest)(nil), "catalog.UpdateProductRequest")
	proto.RegisterType((*UpdateProductResponse)(nil), "catalog.UpdateProductResponse")
	proto.RegisterType((*GetProductsRequest)(nil), "catalog.GetProductsRequest")
	proto.RegisterType((*GetProductsResponse)(nil), "catalog.GetProductsResponse")
}

func init() {
	proto.RegisterFile("byteintellect_protos/pkg/catalog_v1/catalog.proto", fileDescriptor_8238c2673550e54a)
}

var fileDescriptor_8238c2673550e54a = []byte{
	// 734 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0xcf, 0x4e, 0xdb, 0x40,
	0x10, 0xc6, 0x95, 0x04, 0x42, 0x98, 0x94, 0x1c, 0x96, 0x04, 0x12, 0x03, 0x09, 0xb2, 0x2a, 0xb5,
	0xa2, 0x05, 0x97, 0xf4, 0x46, 0x6f, 0xa5, 0x15, 0xd0, 0x43, 0x85, 0xd2, 0x72, 0xe9, 0xc5, 0x5d,
	0x9c, 0x91, 0x63, 0xe1, 0x78, 0xdd, 0xf5, 0x06, 0x85, 0xa2, 0x4a, 0x55, 0x5f, 0x81, 0xf7, 0xea,
	0xa5, 0xaf, 0xd0, 0x07, 0xa9, 0xbc, 0x5e, 0xff, 0xad, 0xd3, 0x03, 0xa8, 0xb7, 0xdd, 0x99, 0xd5,
	0xfe, 0xbe, 0x9d, 0xfd, 0x66, 0x6d, 0x38, 0xbc, 0xbc, 0x11, 0xe8, 0x78, 0x02, 0x5d, 0x17, 0x2d,
	0x61, 0xfa, 0x9c, 0x09, 0x16, 0x18, 0xfe, 0x95, 0x6d, 0x58, 0x54, 0x50, 0x97, 0xd9, 0xe6, 0xf5,
	0x61, 0x3c, 0x3c, 0x90, 0x59, 0xb2, 0xa2, 0xa6, 0x1a, 0xb1, 0x18, 0x47, 0x99, 0x67, 0x1c, 0xa3,
	0xa4, 0xb6, 0x6d, 0x33, 0x66, 0xbb, 0x68, 0x50, 0xdf, 0x31, 0xa8, 0xe7, 0x31, 0x41, 0x85, 0xc3,
	0xbc, 0x20, 0xca, 0xea, 0x9f, 0xa1, 0x79, 0x4c, 0x05, 0xda, 0x8c, 0xdf, 0xbc, 0x11, 0x8c, 0xec,
	0x42, 0x73, 0x8c, 0x81, 0xc5, 0x1d, 0x3f, 0x5c, 0xd4, 0xad, 0xec, 0x56, 0x9e, 0xae, 0x8e, 0xb2,
	0x21, 0x42, 0x60, 0xc9, 0xa3, 0x53, 0xec, 0x56, 0x65, 0x4a, 0x8e, 0xc9, 0x16, 0xac, 0x3a, 0x53,
	0x6a, 0xa3, 0x39, 0xe3, 0x6e, 0xb7, 0x26, 0x13, 0x0d, 0x19, 0xb8, 0xe0, 0xae, 0x7e, 0x57, 0x01,
	0x38, 0xe7, 0x6c, 0x3c, 0xb3, 0x44, 0x48, 0x18, 0x40, 0xd3, 0x52, 0x40, 0xd3, 0x19, 0x2b, 0x02,
	0xc4, 0xa1, 0xb3, 0x31, 0xd9, 0x80, 0x3a, 0x9d, 0xb2, 0x99, 0x27, 0x24, 0xa2, 0x3a, 0x52, 0xb3,
	0x10, 0x32, 0xa5, 0x9e, 0x39, 0x61, 0x33, 0x1e, 0x48, 0x48, 0x6d, 0xd4, 0x98, 0x52, 0xef, 0x34,
	0x9c, 0xe7, 0x15, 0x2c, 0xe5, 0x15, 0x24, 0x92, 0x97, 0x53, 0xc9, 0xfa, 0x09, 0x74, 0x8e, 0x39,
	0x52, 0x81, 0xf1, 0xe9, 0x47, 0xf8, 0x65, 0x86, 0x81, 0x20, 0x07, 0xb0, 0xe2, 0xd3, 0x1b, 0x97,
	0xd1, 0x48, 0x5b, 0x73, 0xd8, 0x3e, 0x88, 0x8b, 0x9d, 0x29, 0xd4, 0x28, 0x5e, 0xa4, 0xbf, 0x83,
	0x8d, 0xe2, 0x46, 0x81, 0xcf, 0xbc, 0x00, 0xc9, 0x0b, 0x68, 0x70, 0x35, 0xfe, 0xe7, 0x56, 0xc9,
	0x2a, 0x7d, 0x02, 0x9d, 0x0b, 0x7f, 0xfc, 0x70, 0x51, 0xc5, 0x22, 0x57, 0x8b, 0x45, 0x0e, 0x55,
	0x17, 0x49, 0xf7, 0x56, 0x7d, 0x05, 0xed, 0x13, 0x14, 0x2a, 0xe7, 0x60, 0x10, 0x8b, 0x1e, 0x40,
	0x33, 0x40, 0xca, 0xad, 0x89, 0x29, 0x70, 0x2e, 0xe2, 0x9b, 0x8e, 0x42, 0x1f, 0x71, 0x2e, 0x48,
	0x0f, 0x1a, 0x3e, 0x72, 0xd3, 0xa7, 0x76, 0x64, 0xa7, 0xda, 0x68, 0xc5, 0x47, 0x7e, 0x4e, 0x6d,
	0x24, 0x9b, 0xe1, 0x81, 0x6d, 0x34, 0x3d, 0xa6, 0xae, 0xba, 0x1e, 0x4e, 0xdf, 0x33, 0x7d, 0x0e,
	0x9d, 0x02, 0x4c, 0xe9, 0x7e, 0x0e, 0x75, 0x8e, 0xc1, 0xcc, 0x0d, 0x41, 0xb5, 0x85, 0xaa, 0xd5,
	0x1a, 0xd2, 0x86, 0x65, 0xc1, 0x04, 0x75, 0x15, 0x37, 0x9a, 0x84, 0x2e, 0xf2, 0x70, 0x2e, 0x22,
	0x45, 0x21, 0xb7, 0x31, 0x6a, 0x84, 0x81, 0x50, 0x92, 0xfe, 0x16, 0xda, 0xd1, 0x45, 0x2b, 0x33,
	0xc7, 0xc7, 0xdc, 0x2f, 0xde, 0xcd, 0x7a, 0x42, 0x4e, 0x6d, 0x9f, 0xfa, 0xe5, 0x34, 0x36, 0x5e,
	0xb2, 0x8d, 0x3a, 0x80, 0xf1, 0x57, 0xe1, 0x4b, 0x37, 0x4a, 0xeb, 0x3e, 0x86, 0x76, 0x74, 0x87,
	0x0f, 0x12, 0x44, 0x76, 0x00, 0xfc, 0x28, 0x9c, 0x5a, 0x65, 0x55, 0x45, 0xce, 0xa4, 0xde, 0x02,
	0xe5, 0xbe, 0x7a, 0x1d, 0x20, 0x27, 0x28, 0x54, 0xea, 0xff, 0xba, 0x64, 0x06, 0xeb, 0x39, 0x94,
	0x92, 0xfc, 0xac, 0xe0, 0x91, 0x52, 0xc1, 0xf7, 0xb7, 0xc8, 0xf0, 0xe7, 0x32, 0xb4, 0x8e, 0xa3,
	0x1d, 0x3f, 0x20, 0xbf, 0x76, 0x2c, 0x24, 0x1c, 0x5a, 0xf9, 0xe7, 0x81, 0xf4, 0x53, 0x63, 0x96,
	0x3d, 0x40, 0xda, 0x60, 0x61, 0x5e, 0xd5, 0x71, 0xf0, 0xe3, 0xd7, 0xef, 0xbb, 0x6a, 0x4f, 0x6f,
	0x19, 0xd1, 0x87, 0x40, 0x75, 0xc2, 0x51, 0x72, 0xa3, 0xdf, 0x2b, 0xd0, 0xca, 0x77, 0x77, 0x06,
	0x5a, 0xfa, 0xc0, 0x64, 0xa0, 0xe5, 0xcf, 0x82, 0xbe, 0x2f, 0xa1, 0x4f, 0x86, 0xdb, 0x79, 0xa8,
	0x71, 0x9b, 0x79, 0x67, 0xbe, 0xa5, 0x12, 0x7c, 0x58, 0xcb, 0xb5, 0x29, 0xd9, 0x49, 0x00, 0x65,
	0x6f, 0x85, 0xd6, 0x5f, 0x94, 0x56, 0xf8, 0x5d, 0x89, 0xd7, 0xb4, 0x4e, 0x01, 0x1f, 0xf9, 0xe4,
	0xa8, 0xb2, 0x47, 0xa6, 0xb0, 0x96, 0xeb, 0xab, 0x0c, 0xb1, 0xac, 0x6d, 0xb5, 0xfe, 0xa2, 0xb4,
	0x22, 0xee, 0x48, 0xe2, 0xa6, 0xfe, 0x28, 0x24, 0xaa, 0x76, 0xc8, 0xd4, 0xf8, 0x2b, 0xac, 0xe5,
	0xda, 0x22, 0x83, 0x2b, 0x6b, 0x4a, 0xad, 0xbf, 0x28, 0xad, 0x70, 0x7b, 0x12, 0xf7, 0x78, 0xd8,
	0xcb, 0xe2, 0x8c, 0xdb, 0xb4, 0x33, 0x33, 0xc5, 0x9d, 0x40, 0x33, 0xe3, 0x6e, 0xb2, 0x95, 0xad,
	0x5d, 0xa1, 0xbd, 0xb4, 0xed, 0xf2, 0xa4, 0xa2, 0xf6, 0x25, 0xb5, 0xab, 0xad, 0xe7, 0xa8, 0x49,
	0x51, 0x5f, 0x6f, 0x7d, 0xea, 0xe5, 0x7f, 0x3c, 0x5e, 0xa5, 0xc3, 0xcb, 0xba, 0xfc, 0x83, 0x78,
	0xf9, 0x27, 0x00, 0x00, 0xff, 0xff, 0x40, 0x96, 0x06, 0xed, 0xb1, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CatalogServiceClient interface {
	CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error)
	UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error)
	GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error)
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error)
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error)
	GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error)
}

type catalogServiceClient struct {
	cc *grpc.ClientConn
}

func NewCatalogServiceClient(cc *grpc.ClientConn) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error) {
	out := new(CreateCategoryResponse)
	err := c.cc.Invoke(ctx, "/catalog.CatalogService/CreateCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error) {
	out := new(UpdateCategoryResponse)
	err := c.cc.Invoke(ctx, "/catalog.CatalogService/UpdateCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	out := new(GetCategoriesResponse)
	err := c.cc.Invoke(ctx, "/catalog.CatalogService/GetCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error) {
	out := new(CreateProductResponse)
	err := c.cc.Invoke(ctx, "/catalog.CatalogService/CreateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error) {
	out := new(UpdateProductResponse)
	err := c.cc.Invoke(ctx, "/catalog.CatalogService/UpdateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error) {
	out := new(GetProductsResponse)
	err := c.cc.Invoke(ctx, "/catalog.CatalogService/GetProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
type CatalogServiceServer interface {
	CreateCategory(context.Context, *CreateCategoryRequest) (*CreateCategoryResponse, error)
	UpdateCategory(context.Context, *UpdateCategoryRequest) (*UpdateCategoryResponse, error)
	GetCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesResponse, error)
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error)
	UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error)
	GetProducts(context.Context, *GetProductsRequest) (*GetProductsResponse, error)
}

func RegisterCatalogServiceServer(s *grpc.Server, srv CatalogServiceServer) {
	s.RegisterService(&_CatalogService_serviceDesc, srv)
}

func _CatalogService_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalog.CatalogService/CreateCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CreateCategory(ctx, req.(*CreateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalog.CatalogService/UpdateCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).UpdateCategory(ctx, req.(*UpdateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalog.CatalogService/GetCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetCategories(ctx, req.(*GetCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalog.CatalogService/CreateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalog.CatalogService/UpdateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalog.CatalogService/GetProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetProducts(ctx, req.(*GetProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CatalogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCategory",
			Handler:    _CatalogService_CreateCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _CatalogService_UpdateCategory_Handler,
		},
		{
			MethodName: "GetCategories",
			Handler:    _CatalogService_GetCategories_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _CatalogService_CreateProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _CatalogService_UpdateProduct_Handler,
		},
		{
			MethodName: "GetProducts",
			Handler:    _CatalogService_GetProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "byteintellect_protos/pkg/catalog_v1/catalog.proto",
}
